version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: docker/laravel/Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/laravel/supervisord.conf:/etc/supervisord.conf
    networks:
      - app_network
    depends_on:
      - mysql
    command: sh -c "cp .env.example .env && composer install && php artisan migrate && php artisan config:cache && php artisan route:cache && php artisan view:cache && php-fpm"

  nginx:
    build:
      context: ./backend
      dockerfile: docker/nginx/Dockerfile
    image: nginx_server
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network
    depends_on:
      - laravel

  mysql:
    build:
      context: ./backend/docker/mysql
      dockerfile: Dockerfile
    image: mysql_custom
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bravi
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  angular:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    image: angular_app
    container_name: angular_app
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    networks:
      - app_network
    command: >
      sh -c "npm install &&
             ng serve --host 0.0.0.0"

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
