version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: docker/laravel/Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network
    depends_on:
      - mysql

  nginx:
    build:
      context: ./backend
      dockerfile: docker/nginx/Dockerfile
    image: nginx_server
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  angular:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    image: angular_app
    container_name: angular_app
    restart: unless-stopped
    ports:
      - "4200:4200"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
